# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bootsSimuOnce <- function(data_end, data_exo, lag_end, lag_exo, sampleSize, AList_eachProb) {
    .Call(`_bayesQVAR_bootsSimuOnce`, data_end, data_exo, lag_end, lag_exo, sampleSize, AList_eachProb)
}

.calQIRFwithA <- function(AList_eachHorizon, sigmaSqrt, A0, idx_impulse, idx_response, n_end, lag_end, mean, A_mean) {
    .Call(`_bayesQVAR_calQIRFwithA`, AList_eachHorizon, sigmaSqrt, A0, idx_impulse, idx_response, n_end, lag_end, mean, A_mean)
}

.calQIRFOnce <- function(modelSpecif, names_impulse, names_response, sigmaSqrt, horizon, probPath, mean = FALSE, counterfactual = NULL) {
    .Call(`_bayesQVAR_calQIRFOnce`, modelSpecif, names_impulse, names_response, sigmaSqrt, horizon, probPath, mean, counterfactual)
}

.constDesignMat <- function(data_end, data_exo = NULL, lag_end = 1L, lag_exo = 0L) {
    .Call(`_bayesQVAR_constDesignMat`, data_end, data_exo, lag_end, lag_exo)
}

.estBQVAR <- function(data_end, lag, alpha, data_exo = NULL, prior = NULL, samplerSetting = NULL, method = "bayes-al", printFreq = 10L, mute = FALSE) {
    .Call(`_bayesQVAR_estBQVAR`, data_end, lag, alpha, data_exo, prior, samplerSetting, method, printFreq, mute)
}

.estMultiBQVAR <- function(modelSpecif, alphaMat) {
    .Call(`_bayesQVAR_estMultiBQVAR`, modelSpecif, alphaMat)
}

.estVARbyOLS <- function(Y, X) {
    .Call(`_bayesQVAR_estVARbyOLS`, Y, X)
}

.estBVAR <- function(data_end, lag, data_exo = NULL, prior, samplerSetting) {
    .Call(`_bayesQVAR_estBVAR`, data_end, lag, data_exo, prior, samplerSetting)
}

.estSigmaOfBVAR <- function(data_end, lag, data_exo = NULL, prior, samplerSetting) {
    .Call(`_bayesQVAR_estSigmaOfBVAR`, data_end, lag, data_exo, prior, samplerSetting)
}

.forecastQuant <- function(modelSpecif, horizon, probPath, mean = FALSE) {
    .Call(`_bayesQVAR_forecastQuant`, modelSpecif, horizon, probPath, mean)
}

